### ISSUE TITLE
Does the latest keycloak image require HTTPS for the initial login and later?

### ISSUE THREAD

**Issue by nelsonjchen** [PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications#13]
I'm working through the book right now but there seems to be some errors from the demo apps calling to keycloak because keycloak seems to require HTTPS at the moment out of the box. I found that you can disable the requirements by going into the realms (?) and unchecking a box.

**Comment by nelsonjchen** [comment]
You also can't do the initial login.

**Comment by nelsonjchen** [comment]
Hmm, odd, I guess it must only apply to my M1 Macbook's built from master image since the x86 one doesn't boot. This might be a sign of things to come though.

**Comment by stianst** [comment]
There's not been any changes in this regard to Keycloak. It has always required SSL for external IP addresses by default, but not for internal. Are you opening Keycloak on "localhost", or on some other domain/IP?

**Comment by nelsonjchen** [comment]
Hmm, the issue may have been my VPN. I rebuilt the image and it doesn't look like it's an issue anymore. How mysterious. Sorry for the bother.
