### ISSUE TITLE
[Ch 2, frontend] unable to invoke secure endpoint from frontend

### ISSUE THREAD

**Issue by khall1026** [PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications#19]
I created and assigned the realm/user/group/role/client, as specified in the book, but invoking the service from the frontend still gives Access Denied.

<img width="584" alt="image" src="https://user-images.githubusercontent.com/41909622/174906447-03c5e1f7-30f3-41ff-b2e1-c71654b52fbd.png">

**Comment by stianst** [comment]
Can you show the output of the access token? Also, have you made sure you've configured the correct URLs for Keycloak in the service as that's required to verify the iss field in the token.

**Comment by khall1026** [comment]
Are you referring to the URL fields in myclient?  They're set to localhost:8000 as specified in Ch2.  There are no references to localhost:3000 in the KC admin page.

Here's the access token:
{
  "exp": 1655915600,
  "iat": 1655915300,
  "auth_time": 1655914855,
  "jti": "644c2229-859d-482b-b81e-040a91ad839b",
  "iss": "http://localhost:8080/realms/myrealm",
  "aud": "account",
  "sub": "be80e226-2848-4a4f-a595-1d50e5a47e80",
  "typ": "Bearer",
  "azp": "myclient",
  "nonce": "d39407ce-2e14-41db-a5e2-26754d2d4aae",
  "session_state": "996b6ae2-3b67-482c-a0bf-d2c6c43e904b",
  "acr": "0",
  "allowed-origins": [
    "http://localhost:8000"
  ],
  "realm_access": {
    "roles": [
      "default-roles-myrealm",
      "offline_access",
      "uma_authorization",
      "myrole"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "openid email profile",
  "sid": "996b6ae2-3b67-482c-a0bf-d2c6c43e904b",
  "email_verified": false,
  "name": "Kurt Hall",
  "preferred_username": "keh1",
  "given_name": "Kurt",
  "family_name": "Hall",
  "email": "kurt.hall@nasdaq.com"
}

**Comment by stianst** [comment]
My guess here is that you are using the new Quarkus distribution of Keycloak, and not the legacy distribution? That removes '/auth' from the default base url of Keycloak.

Options are either to configure it to use '/auth' as the legacy distribution does, use the legacy distribution, or remove '/auth' as you've done in the sample applications.
