### ISSUE TITLE
Examples are not working with newer versions of Keycloak

### ISSUE THREAD

**Issue by stianst** [PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications#26]
At the time of writing the book and examples Keycloak 12 was the most recent version. Since then a completely new distribution of Keycloak was introduced, which was based on Quarkus, rather than WildFly. This new distribution while introducing a significantly easier way to configure Keycloak also introduces a number of breaking changes, including:

* How you configure the Keycloak server
* How you run and configure the container
* Removes `/auth` from the default URLs

A 2nd edition of the book is in development, which will update to the latest version of Keycloak. However, in the meantime to follow the book one option is to use the legacy distribution of Keycloak, where the latest release was 19.0.3. You can download this release [here](https://github.com/keycloak/keycloak/releases/tag/19.0.3). Bear in mind this version has not received any updates for quite some time, and hence does have several known CVEs. Do not use this version in production!

An alternative is to use the most recent version of Keycloak, combined with looking at the [Migration to Quarkus distribution](https://www.keycloak.org/migration/migrating-to-quarkus) guide and the [Server Guides](https://www.keycloak.org/guides#server).

To workaround the issue with the removed `/auth` in the Keycloak URLs you can either start Keycloak with the previous URLs by adding like this:

```
bin/kc.sh start-dev --http-relative-path=auth
```

Or, you can change the URLs used in the examples with setting the `KC_URL` environment variable prior to building and running the samples:

```
export KC_URL=http://localhost:8080
```

**Comment by MauricioPenteado** [comment]
I fixed this aligning realm names.
It is because of the following:
```
In the book: It describes to create myhelm
Frontend example:   on index.html file:   var kc = new Keycloak({ realm: 'Myrealm', clientId: 'myclient' });
Backend example:    on keycloak.json file:    {  "realm": "myrealm",  ...  }
```
If the capital letters are not aligned it will not work.

**Comment by stianst** [comment]
For more recent releases of Keycloak please use the 2nd edition of the book
