### ISSUE TITLE
ch2/frontend has errors

### ISSUE THREAD

**Issue by markgoho** [PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications#8]
after installing dependencies and running the front end, we get this in Chrome:
![image](https://user-images.githubusercontent.com/9759954/127204476-6313ffc2-e90e-4d7f-89c4-9ddb8ce0df7c.png)

**Comment by pedroigor** [comment]
@markgoho Thanks for raising this issue. Could you check if the changes from https://github.com/PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications/pull/10 solve the problem.

I'm still not sure why this error is happening now, but increasing the timeout through the `messageReceiveTimeout` should help.
